server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

# application.yml
app:
  member-api:
    base-url: http://localhost:8081 # Exemplo: URL da sua API mockada ou microserviço de membros

# Swagger - sem customização, vai usar as rotas padrão:
# http://localhost:8085/swagger-ui.html

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Feign Client - tempo de timeout básico
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
